### ISSUE TITLE
Optimize ping() method

### ISSUE THREAD

**Issue by spyinx** [valkey-io/valkey-py#146]
ping() method in ManagementCommands
https://github.com/valkey-io/valkey-py/blob/c490780a1d7b629317e5c0d976ec13dd64de8e55/valkey/commands/core.py#L1203-L1209

when i use ping() method in class ManagementCommands, i have some questions：
- it does't support message param, but ping() in class Pubsub does, why?
https://github.com/valkey-io/valkey-py/blob/c490780a1d7b629317e5c0d976ec13dd64de8e55/valkey/client.py#L1079-L1084
- ping() method has kwargs to allow extra options, but does this method really need it? if you add some extra options, it will raise a exception because of the callback in _ValkeyCallbacks
```python
>>> from valkey import Valkey
>>> r = Valkey(host="127.0.0.1", port=6888, password='xxxxx')
>>> r.ping()
True
>>> r.ping("hello")
Traceback (most recent call last):
  File "<python-input-3>", line 1, in <module>
    r.ping("hello")
    ~~~~~~^^^^^^^^^
TypeError: ManagementCommands.ping() takes 1 positional argument but 2 were given
>>> r.ping(message="hello")
Traceback (most recent call last):
  File "<python-input-4>", line 1, in <module>
    r.ping(message="hello")
    ~~~~~~^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/env-3.13/lib/python3.13/site-packages/valkey/commands/core.py", line 1211, in ping
    return self.execute_command("PING", **kwargs)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/env-3.13/lib/python3.13/site-packages/valkey/client.py", line 570, in execute_command
    response = conn.retry.call_with_retry(
        lambda: self._send_command_parse_response(
    ...<2 lines>...
        lambda error: self._disconnect_raise(conn, error),
    )
  File "/root/.pyenv/versions/env-3.13/lib/python3.13/site-packages/valkey/retry.py", line 62, in call_with_retry
    return do()
  File "/root/.pyenv/versions/env-3.13/lib/python3.13/site-packages/valkey/client.py", line 571, in <lambda>
    lambda: self._send_command_parse_response(
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        conn, command_name, *args, **options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
  File "/root/.pyenv/versions/env-3.13/lib/python3.13/site-packages/valkey/client.py", line 543, in _send_command_parse_response
    return self.parse_response(conn, command_name, **options)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/env-3.13/lib/python3.13/site-packages/valkey/client.py", line 600, in parse_response
    return self.response_callbacks[command_name](response, **options)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
TypeError: <lambda>() got an unexpected keyword argument 'message'
>>> 
```
**Is there any historical reasons to do so?** Now i do some changes for ping:
- ping():
```python
    # in class ManagementCommands
    def ping(self, message=None, **kwargs) -> ResponseT:
        """
        Ping the Valkey server

        For more information see https://valkey.io/commands/ping
        """
        args = ["PING", message] if message is not None else ["PING"]
        return self.execute_command(*args, message=message)
```
- add new callback for ping command:
```python
# import safe_str
from valkey.utils import str_if_bytes, safe_str  

def parse_ping(response, **options):
    response = str_if_bytes(response)
    message = "PONG" if options.get("message") is None else options.get("message")
    return response == safe_str(message)


_ValkeyCallbacks = {
    # ...
    # "PING": lambda r: str_if_bytes(r) == "PONG",
    "PING": parse_ping,
    
    # ...
}
```
then we can try the new ping() method:
```python
>>> from valkey import Valkey
>>> r = Valkey(host="127.0.0.1", port=6888, password='xxxxx')
>>> r.ping()
True
>>> r.ping(0)
True
>>> r.ping("hello")
True
>>> r.ping(xxx=0)
True
>>> r.ping("abc", xxx=0)
True
```

**Comment by spyinx** [comment]
maybe ping() method just use to test valkey server is alive or not, so there is no need to add extra message,  but why use **kwargs to receive extra params since the default callback will occurs exception?

**Comment by aiven-sal** [comment]
Hi!
In general, we don't have a lot of insight about why certain things are done in a certain way, because we are not the original authors of most of the code in valkey-py. Your guess is as good as mine here.

Your proposal makes sense to me.

But I'd rewrite
```
 message = "PONG" if options.get("message") is None else options.get("message")
```
as
```
 message = options.get("message", "PONG")
```

**Comment by aiven-sal** [comment]
Would you like to make a PR?

**Comment by spyinx** [comment]
> Hi! In general, we don't have a lot of insight about why certain things are done in a certain way, because we are not the original authors of most of the code in valkey-py. Your guess is as good as mine here.
> 
> Your proposal makes sense to me.
> 
> But I'd rewrite
> 
> ```
>  message = "PONG" if options.get("message") is None else options.get("message")
> ```
> 
> as
> 
> ```
>  message = options.get("message", "PONG")
> ```

there is a problem using `message = options.get("message", "PONG")`, because `options.get("message")` will get None when message is None, it will not be "PONG":
```python
>>> data = {"message": None}
>>> data.get("message", "PONG") == None
True
```

**Comment by spyinx** [comment]
> Would you like to make a PR?

i will make a pr, thanks for your reply,  i'll continue to fix real bugs in valkey-py and try to make it better. now i only read valkey's command methods, so my opinion may not be right or even wrong, but i will think more before asking questions.

**Comment by spyinx** [comment]
it was my fault to think that this issue was easy to do, i didn't understand the code well enough. adding a message that would affect the callback of the cluster connection in ping. Although I found the callback code , I thought it was unnecessary to modify both, so I closed my pr. I will test more before creating a pr in the future. thanks again  @aiven-sal

**Comment by aiven-sal** [comment]
No problem!

**Comment by mkmkme** [comment]
@spyinx any progress about this or perhaps just from the tests side?

**Comment by spyinx** [comment]
> [@spyinx](https://github.com/spyinx) any progress about this or perhaps just from the tests side?

hello, @mkmkme , sorry for late response. For the test errors mentioned earlier,  it seems necessary to comment out the 'PING' in the following code：
```python
    # in cluster.py

    RESULT_CALLBACKS = dict_merge(
        list_keys_to_dict(["PUBSUB NUMSUB", "PUBSUB SHARDNUMSUB"], parse_pubsub_numsub),
        list_keys_to_dict(
            ["PUBSUB NUMPAT"], lambda command, res: sum(list(res.values()))
        ),
        list_keys_to_dict(
            ["KEYS", "PUBSUB CHANNELS", "PUBSUB SHARDCHANNELS"], merge_result
        ),
        list_keys_to_dict(
            [
                # remove PING here
                # "PING",   
                "CONFIG SET",
                "CONFIG REWRITE",
                "CONFIG RESETSTAT",
                "CLIENT SETNAME",
                "BGSAVE",
                "SLOWLOG RESET",
                "SAVE",
                "MEMORY PURGE",
                "CLIENT PAUSE",
                "CLIENT UNPAUSE",
            ],
            lambda command, res: all(res.values()) if isinstance(res, dict) else res,
        ),
        # ...
    )
```
but I'm not sure what impact this will have on the entire valkey-py codebase, perhaps my issue isn't well-raised and doesn't make much sense. Can you give me some advice, or we can close the issue.

**Comment by mkmkme** [comment]
Thanks! I'll have a look anyways, but it'll have to be a low prio for now

**Comment by spyinx** [comment]
> Thanks! I'll have a look anyways, but it'll have to be a low prio for now

ok，thanks
