### ISSUE TITLE
Discourage the use of `del` 

### ISSUE THREAD

**Issue by mkmkme** [valkey-io/valkey-py#160]
Proper client workflow should utilize `__enter__` and `__exit__` instead.

So, instead of using

```python
import valkey
r = valkey.Valkey(host="localhost", port=6379)
r.set("foo", "bar")
```

one should use

```python
import valkey
with valkey.Valkey(host="localhost", port=6379) as r:
    r.set("foo", "bar")
```

This should be properly documented.

Related to #158

**Comment by mkmkme** [comment]
Actually on current `main` this workflow doesn't work. I wonder why...

```
>>> import valkey
>>> with valkey.Valkey(host="localhost", port=6379) as r:
...     print(r)
...
<valkey.client.Valkey(<valkey.connection.ConnectionPool(<valkey.connection.Connection(host=localhost,port=6379,db=0)>)>)>
>>> exit()
Exception ignored in: <function Valkey.__del__ at 0x7f3038b4e520>
Traceback (most recent call last):
  File "/home/mikhail.koviazin/workspace/valkey-py-clean/valkey/client.py", line 521, in __del__
  File "/home/mikhail.koviazin/workspace/valkey-py-clean/valkey/client.py", line 536, in close
  File "/home/mikhail.koviazin/workspace/valkey-py-clean/valkey/connection.py", line 1179, in disconnect
  File "/home/mikhail.koviazin/workspace/valkey-py-clean/valkey/connection.py", line 1083, in _checkpid
TypeError: 'NoneType' object is not callable
```

**Comment by mkmkme** [comment]
Okay, `with`-statement doesn't help since it doesn't create its own scope and the variable leaks up. Because of that using context manager won't help. Closing
